services:
  # ==========================================
  # Backedn Service
  # ==========================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: orion-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LOGSTASH_HOST=orion-logstash
      - LOGSTASH_PORT=5044
    networks:
      - orion-elk-net
      - orion-network
    restart: unless-stopped

  # ==========================================
  # Frontend Service
  # ==========================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: orion-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - orion-network
    restart: unless-stopped

networks:
  orion-network:
    driver: bridge
  orion-elk-net:
    external: true
