sonar.projectKey=fennecdevsolutions_OpenClassrooms_P7_CICD_CRM
sonar.organization=fennecdevsolutions
sonar.host.url=https://sonarcloud.io
sonar.projectName=Orion CRM
sonar.modules=back,front

# Backend configuration
back.sonar.sources=src/main/java
back.sonar.tests=src/test/java
back.sonar.java.binaries=build/classes/java/main
back.sonar.junit.reportPaths=build/test-results/test
back.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Frontend configuration
front.sonar.sources=src
front.sonar.exclusions=src/**/*.spec.ts, src/test.ts
front.sonar.tests=src
front.sonar.test.inclusions=src/**/*.spec.ts
front.sonar.javascript.lcov.reportPaths=coverage/microcrm/lcov.info