input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # Placeholder
}

output {
  # Send to elastic search
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orion-crm-logs-%{+YYYY.MM.dd}"
  }
  
  # Debug: display logs in logstack console
  stdout { codec => rubydebug }
}