sonar.projectKey=fennecdevsolutions_OpenClassrooms_P7_CICD_CRM
sonar.organization=fennecdevsolutions
sonar.host.url=https://sonarcloud.io

sonar.projectName=Orion CRM (Frontend)

# Source to analyse (exclude test files)
sonar.sources=src
sonar.exclusions=src/**/*.spec.ts

# Tests and reports paths
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/microcrm/lcov.info

sonar.sourceEncoding=UTF-8